import type { Metadata } from "next";
import { DM_Mono, Oswald } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/navbar/Navbar";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const suisseBold = localFont({
  src: "./fonts/suisse-intl-bold.otf",
  variable: "--font-suisse-bold",
});

const suisseRegular = localFont({
  src: "./fonts/suisse-intl-regular.ttf",
  variable: "--font-suisse-regular",
});

const dmMono = DM_Mono({
  weight: ["300", "400", "500"],
  variable: "--font-dm-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${suisseBold.variable} ${suisseRegular.variable} ${oswald.variable} ${dmMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
